# Task 1: Problem # 2:

In this laboratory task, you will execute multivariable linear regression through the utilization of the Matrix-Vector 
Multiplication approach with Gradient Descent. Please follow the solution that I provided for the Midterm exam. 
Show me that your Python code gives the same result that I have in the solution. 

Determine the parametrs for linear regression, compute both theta0,theta1,theta2,theta3,theta4 and cost function for each iteration.

In [2]:
import numpy as np

In [4]:
import numpy as np

def add_ones_column(data):
    return np.column_stack([np.ones(data.shape[0]), data])

def gradient_descent(x, y, θ, alpha, num_iterations):
    for iteration in range(num_iterations):
        predictions = np.dot(x, θ)
        errors = predictions - y
        gradient = np.dot(x.T, errors) / len(y)
        
        # Update parameters θ using the gradient
        θ -= (alpha * gradient)

        # Calculate the cost function after each iteration.
        updated_predictions = np.dot(x, θ)
        updated_errors = updated_predictions - y
        cost = np.mean(updated_errors ** 2) / 2
        
        print(f"Iteration {iteration + 1}:")
        print(" θ values:", θ)
        print("Cost function:", cost)
        print()

# Input data
data = np.array([
    [0.5, 1.0, 2.0, -0.5],
    [1.0, 0.2, 2.0, 1.0],
    [1.0, 0.2, 0.5, 0.5],
    [-1.0, -0.5, 0.2, 0.0]
])

# Separate the features x and y
x = data[:, :-1]
y = data[:, -1]

# Adding 1's column to the features for the bias term θ0
x = add_ones_column(x)

# Initialize parameters θ with zeros
θ = np.zeros(x.shape[1])

# Set hyperparameters
alpha = 0.5
num_iterations = 3

# Perform Gradient Descent
gradient_descent(x, y, θ, alpha, num_iterations)


Iteration 1:
 θ values: [ 0.125    0.15625 -0.025    0.15625]
Cost function: 0.14647841796875

Iteration 2:
 θ values: [ 0.06921875  0.16550781 -0.134125    0.02019531]
Cost function: 0.1196066831010437

Iteration 3:
 θ values: [ 0.13180098  0.25668306 -0.17963629  0.08681743]
Cost function: 0.10054495192180492



ii) After 3rd iteration , predict the outputs for given i/p data

In [5]:
# New data for prediction
data1 = np.array([
    [0.1, 0.2, 0.3],
    [-1, 0.1, 1],
    [0.5, 0.3, -1],
    [1, 0.5, 0.3]
])

# Adding 1's column to the features for the bias term θ0
x1 = add_ones_column(data1)

# Make predictions using the trained θ values
predicted_output = np.dot(x1, θ)
print("Predicted output values:", predicted_output)

Predicted output values: [ 0.14758725 -0.05602828  0.11943419  0.32471112]


# Task 2: Problem # 4:

In this laboratory task, you will execute Polynomial linear regression through the utilization of the Matrix-Vector 
Multiplication approach with Gradient Descent.

Please follow the solution that I provided for the Midterm exam. Show me that your Python code gives the same result that 
I have in the solution. 


1. add a new feature x2=x^2

In [68]:
# Data set
data = np.array([
    [89, 96],
    [72, 74],
    [94, 87],
    [69, 78]
])

# Adding a new feature x2 = x^2
x = data[:, :-1]
y = data[:, -1]
new_data = np.column_stack([x, x[:, 0] ** 2,y])
print("new data set: x2 = x^2:",new_data)


new data set: x2 = x^2: [[  89 7921   96]
 [  72 5184   74]
 [  94 8836   87]
 [  69 4761   78]]


2. Feature normalize each feature so that each feature has zero mean and unit varience, report new features are now in new table.

In [69]:
x = new_data[:, :-1]

# mean and standard deviation for each feature
mean = np.mean(x, axis=0)
std = np.std(x, axis=0, ddof=1) 

# Feature normalize
normalized_feature = (x - mean) / std

print("New dataset with normalized features:\n", normalized_feature)

New dataset with normalized features:
 [[ 0.64746735  0.61994303]
 [-0.72840077 -0.74238862]
 [ 1.05213445  1.0753809 ]
 [-0.97120103 -0.95293531]]


3. given initialvalues theta0=theta1=theta2=theta3=0 and learn rate alpha=0.75 , compute N=3 iterations of gradient descentusing feature normalized training data and determine the parametrs for polynomial regression. Compute both theta0,theta1,theta2,theta3 and cost function for each iteration 

In [77]:
new_data_set = np.column_stack([x,y])

# Separate features x and y
x = new_data_set[:,:-1]
y = new_data_set[:,-1]

# Adding 1's column to the features for the bias term θ0
X = np.column_stack([np.ones(x.shape[0]), x])
print("new data set:",new_data_set)

# Initialize parameters θ with zeros
θ = np.zeros(X.shape[1])
alpha = 0.75
N = 3
M = 4

# Gradient Descent
for iteration in range(N):
    predictions = np.dot(X, θ)
    errors = predictions - y
    gradient = np.dot(X.T, errors)
    
    θ -= (alpha * gradient) / M
    print(f"Iteration {iteration + 1}:")
    print("θ values:", θ)

    # cost calculation after each iteration with updated paramers.
    updated_predictions = np.dot(X, θ)
    updated_errors = updated_predictions - y
    cost = np.mean(updated_errors ** 2) / 2

    print("Cost function:", cost)
    print()


new data set: [[ 0.64746735  0.61994303 96.        ]
 [-0.72840077 -0.74238862 74.        ]
 [ 1.05213445  1.0753809  87.        ]
 [-0.97120103 -0.95293531 78.        ]]
X: [[ 1.          1.          1.          1.        ]
 [ 0.64746735 -0.72840077  1.05213445 -0.97120103]
 [ 0.61994303 -0.74238862  1.0753809  -0.95293531]]
Iteration 1:
θ values: [62.8125      4.50697978  4.46380445]
Cost function: 231.80549899506798

Iteration 2:
θ values: [78.515625    3.96865812  3.88231485]
Cost function: 25.94832950809302

Iteration 3:
θ values: [82.44140625  4.06013067  3.93062687]
Cost function: 13.098255504347405



# Task 3: Problem # 5:

1. given initialvalues theta0=theta1=theta2=theta3=0 and learn rate alpha=0.5 , compute k=1 iterations of stochastic gradient descent. after each update for each training example show what theta0,theta1,theta2,theta3 as well as their costs for each training example. once you iterate through all the training examples, calculate what the avg cost over all of the individual costs would be?

In [3]:
# Dataset
data = np.array([
    [0.5, 1, 2, -0.5],
    [1, 0.2, 2, 1],
    [1, 0.2, 0.5, 0.5],
    [-1, -0.5, 0.2, 0]
])

# Extract features (x1, x2, x3) and the target value (y)
features = data[:, :-1]
target = data[:, -1]

# Initialize parameters theta with zeros
theta = np.array([0, 0, 0, 0])
learning_rate = 0.5
total_cost = 0

# Stochastic Gradient Descent iterations
for i in range(len(data)):
    feature_i = np.insert(features[i], 0, 1)  # Adding a bias term
    target_i = target[i]
    
    # Calculate the current prediction
    prediction = np.dot(theta, feature_i)
    error = prediction - target_i
    
    # Update the theta values
    theta = theta - learning_rate * error * feature_i
    
    # Calculate and accumulate the cost for each iteration
    prediction = np.dot(theta, feature_i)
    error = prediction - target_i
    cost_i = (error ** 2)
    total_cost += cost_i
    
    # Display iteration information
    print(f'Training Example {i + 1}:')
    print(f'Theta values: {theta}')
    print(f'Cost: {cost_i}')
    print()

# Calculate the average cost over the iterations
average_cost = total_cost / len(data)
print(f'Average Cost over the Iterations: {average_cost}')


Training Example 1:
Theta values: [-0.25  -0.125 -0.25  -0.5  ]
Cost: 1.12890625

Training Example 2:
Theta values: [ 0.9625  1.0875 -0.0075  1.925 ]
Cost: 23.995302249999995

Training Example 3:
Theta values: [-0.293   -0.168   -0.2586   1.29725]
Cost: 0.13256516902499987

Training Example 4:
Theta values: [-0.424875  -0.036125  -0.1926625  1.270875 ]
Cost: 0.001462584414062506

Average Cost over the Iterations: 6.314559063359765
